### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by nik-wildduck** [Bogdan114/TestTask#1]
1) Написать в readme зачем нужен выпадающий список 16,32 ... и на что это влияет
2) Почему класс cifru1 унаследован от login_password ? Нужно ли сделать по-другому и ,если да, то зачем?
3) Проверить программу на невалидный ввод значений. Дописать необходимые проверки вводимых даннных 
4) Доработать GUI: Исправить надписи, сделать надписи видимыми
![Screenshot from 2022-11-21 15-47-40](https://user-images.githubusercontent.com/11273478/203059140-1697791b-5516-427f-9a4a-5041ac3ab877.png)

**Comment by Bogdan114** [comment]
1. Дописал в README чуть подробней. Продублирую тут, это выбор пользователя относительно AES 16, AES 32  и т.д.
2. Программа организованна именно таким образом, так как в задании указано, что требуется наследование ("Он наследуется от класса, указанного выше"). Сделать по другому мне кажется не нужно, так как если пишется большое приложение подразумевающие разные виды шифрования лаконичней будет выглядеть, когда классы под разные типы шифрования наследуются от базового класса с логином и паролем.
3. Не валидным вводом значений я посчитал отсутствие ввода логина или пароля, в таком случае программа пишет об этом в "Logs".
4. Сделал новый коммит на эту тему. Так как у меня на мониторе выглядит всё нормально, я предположил, что проблема в разрешениях экрана и попытался это исправить.
